### ISSUE TITLE
Use 1d in sedisk

### ISSUE THREAD

**Issue by doomsporting** [luispedro/pymorph#6]
Hi to create a d structuring element in a time series i want to use the pymoprh.sedisk function. But despite the function states that " structuring element can be created on the 1D, 2D or 3D space", i cant use the 1D option because gives me the error "pymorph.sedisk: Supports only 2D structuring elements
".
Do you how to solve it?

Best regards
Thanks

**Comment by luispedro** [comment]
Thanks for the report, `pymorph` is only partially maintained, though.

Isn't a 1-D disk, just `np.ones(radius*2+1)`?

**Comment by doomsporting** [comment]
Thank you for the reply. But being more specific I want a disc filter to run in a time series dataset. To do that I'm using pymorph.sedisk(r=3) to create a structuring filter. Then I use alternative sequential filter (asf)  filter with the structuring filter created previously. But the problem is that the time series is 1D and when I create the pymorph.sedisk(r=3), only creates in 2D. How can I incorporate the suggestion you made?

Thanks

**Comment by luispedro** [comment]
What `pymorph.sedisk(r=3)` would return is `[1,1,1,1,1,1,1]` but as a numpy array (`numpy.array([1,1,1,1,1,1,1])`).

**Comment by doomsporting** [comment]
But doesn't sedisk() create a disk or a semi-sphere structuring element? Sorry im not familiar with pymorph, but as far I know its the only python package that I found to have a sort of circular filter to apply in a time series dataset (vector)

**Comment by luispedro** [comment]
But a 1-D disk is just a series of 1s.

**Comment by doomsporting** [comment]
if i have a vector with values what i want to do is more or less the figure below. The first example is a flat structuring element and the second one is circular. I dont know if its possible using pymorph

![image](https://cloud.githubusercontent.com/assets/11523411/23662259/ddaf6882-0346-11e7-9335-12a7e47a3985.png)

**Comment by doomsporting** [comment]
so what i really want is a non-flat structuring element

**Comment by luispedro** [comment]
Ah, then something like `(r- np.abs(r-np.arange(2*r + 1)))*`?

**Comment by doomsporting** [comment]
Using r- np.abs(r-np.arange(2*r + 1)))**2 as structure element?

**Comment by luispedro** [comment]
Yep

**Comment by doomsporting** [comment]
But in that case if A=r- np.abs(r-np.arange(2*r + 1)))**2  with r=3 gives me an array A= [0 1 4 9 4 1 0] which cannot be applied to pymorph.asf(f, seq="OC", B=A, n=1), taking A as structuring element.
The error:
IndexError: too many indices

**Comment by luispedro** [comment]
Closing as WONTFIX. Pymorph is deprecated in favor of mahotas
