### ISSUE TITLE
python3 installation issue

### ISSUE THREAD

**Issue by alwansm** [luispedro/pymorph#7]
I am trying to install pymorph using python 3 using the command:
 `sudo pip3 install pymorph`
I am getting the following error:
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c95rd_95/pymorph/
`

**Comment by luispedro** [comment]
That's not a lot of info.

In general, pymorph is not being maintained. Have a look at [mahotas](http://mahotas.readthedocs.io) or [skimage](http://scikit-image.org/).

**Comment by alwansm** [comment]
if there is more info needed let me know.
Thanks, i will take a look at mahotas or skimage.

**Comment by luispedro** [comment]
Closing as WONTFIX. Pymorph is deprecated in favor of mahotas
